[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
manifest_sol = "YOUR_PROGRAM_ID"

[programs.devnet]
manifest_sol = "YOUR_PROGRAM_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./.test_wallets/devnet-deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-wall = "pnpm tsx scripts/init-wall.ts"
post-message = "pnpm tsx scripts/post-message.ts" 