[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
manifest_sol = "8RfAJa9Zm4ZpDreRaYbE1g6T5EMgwchMu6jZwTA5kqi9"

[programs.devnet]
manifest_sol = "8RfAJa9Zm4ZpDreRaYbE1g6T5EMgwchMu6jZwTA5kqi9"

[registry]
url = "https://api.apr.dev"

#[provider]
#cluster = "Localnet"
#wallet = "~/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "./.test_wallets/devnet-deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-wall = "npx tsx scripts/init-wall.ts"
post-message = "npx tsx scripts/post-message.ts"
post-message-new = "npx tsx scripts/post-message-new-wallet.ts"
use-existing-wallet = "npx tsx scripts/use-existing-wallet.ts"
